// Mock data for CRM module

export const clients = [
  {
    id: 'CLI-0001',
    name: 'María González',
    type: 'fisica',
    cedula: '001-1234567-8',
    email: 'maria@gmail.com',
    phone: '809-555-0101',
    whatsapp: '809-555-0101',
    address: 'Av. Abraham Lincoln #502, Piantini, Santo Domingo',
    status: 'active',
    segment: 'b2c',
    tier: 'gold',
    points: 340,
    source: 'google_ads',
    assignee: 'Lic. Ramírez',
    createdAt: '2025-09-15',
    lastActivity: '2026-02-14',
    totalSpent: 103000,
    totalOrders: 4,
    activeOrders: 1,
    tags: ['VIP', 'Referido Activo'],
    orders: [
      { id: 'ORD-001247', tramite: 'Constitución de Compañía (SRL)', status: 'processing', amount: 38000, date: '2026-02-03' },
      { id: 'ORD-001120', tramite: 'Registro de Marca (1 clase)', status: 'delivered', amount: 28000, date: '2025-11-10' },
      { id: 'ORD-001055', tramite: 'Contrato de Alquiler', status: 'delivered', amount: 8500, date: '2025-10-01' },
      { id: 'ORD-000980', tramite: 'Contratos (NDA)', status: 'delivered', amount: 6500, date: '2025-09-15' },
    ],
    communications: [
      { type: 'whatsapp', direction: 'outbound', message: 'Sra. González, sus estatutos están listos para revisión.', date: '2026-02-12 09:00', user: 'Sistema' },
      { type: 'email', direction: 'outbound', message: 'Factura ORD-001247 enviada', date: '2026-02-03 09:20', user: 'Sistema' },
      { type: 'whatsapp', direction: 'inbound', message: 'Buenos días, quiero constituir una empresa SRL', date: '2026-02-02 14:30', user: 'Cliente' },
      { type: 'call', direction: 'outbound', message: 'Llamada de seguimiento — interesada en iguala Profesional', date: '2026-01-20 11:00', user: 'Lic. Ramírez' },
      { type: 'email', direction: 'outbound', message: 'Documento de marca entregado — certificado ONAPI', date: '2025-12-15 16:00', user: 'Sistema' },
    ],
    notes: [
      { user: 'Lic. Ramírez', date: '2026-01-20', text: 'Cliente muy satisfecha con servicio de marca. Interesada en iguala profesional para su nueva empresa.' },
      { user: 'Admin', date: '2025-11-10', text: 'Referida por Inversiones Caribe. Dar trato preferencial.' },
    ],
  },
  {
    id: 'CLI-0002',
    name: 'TechStart, SRL',
    type: 'juridica',
    cedula: 'RNC 131-45678-9',
    email: 'legal@techstart.do',
    phone: '829-555-0202',
    whatsapp: '829-555-0202',
    address: 'Torre Empresarial Blue Mall, Piso 8, Santo Domingo',
    status: 'active',
    segment: 'pyme',
    tier: 'silver',
    points: 180,
    source: 'referido',
    assignee: 'Lic. Peña',
    createdAt: '2025-11-20',
    lastActivity: '2026-02-10',
    totalSpent: 64000,
    totalOrders: 3,
    activeOrders: 1,
    tags: ['Startup Tech', 'Iguala Básica'],
    orders: [
      { id: 'ORD-001246', tramite: 'Registro de Marca (1 clase)', status: 'waiting_entity', amount: 28000, date: '2026-01-20' },
      { id: 'ORD-001100', tramite: 'Registro de Nombre Comercial', status: 'delivered', amount: 18000, date: '2025-12-05' },
      { id: 'ORD-001080', tramite: 'Contratos (NDA)', status: 'delivered', amount: 6500, date: '2025-11-20' },
    ],
    communications: [
      { type: 'email', direction: 'outbound', message: 'Marca publicada en boletín ONAPI — período oposición iniciado', date: '2026-02-10 08:10', user: 'Lic. Peña' },
      { type: 'whatsapp', direction: 'inbound', message: 'Alguna novedad con el registro de marca?', date: '2026-02-08 10:00', user: 'Cliente' },
    ],
    notes: [
      { user: 'Lic. Peña', date: '2026-02-10', text: 'Marca en período de oposición. Cliente informado de timeline.' },
    ],
  },
  {
    id: 'CLI-0003',
    name: 'José Martínez',
    type: 'fisica',
    cedula: '402-9876543-2',
    email: 'jose.mtz@hotmail.com',
    phone: '849-555-0303',
    whatsapp: '849-555-0303',
    address: 'Santiago de los Caballeros, Cibao',
    status: 'active',
    segment: 'b2c',
    tier: 'bronze',
    points: 60,
    source: 'calc_laboral',
    assignee: 'Lic. Santos',
    createdAt: '2026-01-28',
    lastActivity: '2026-02-13',
    totalSpent: 17500,
    totalOrders: 1,
    activeOrders: 1,
    tags: ['Pago Parcial'],
    orders: [
      { id: 'ORD-001245', tramite: 'Divorcio por Mutuo Acuerdo', status: 'review', amount: 35000, date: '2026-02-08' },
    ],
    communications: [
      { type: 'whatsapp', direction: 'outbound', message: 'Sr. Martínez, necesitamos la cédula de su cónyuge para avanzar', date: '2026-02-10 10:00', user: 'Lic. Santos' },
      { type: 'whatsapp', direction: 'inbound', message: 'La envío esta semana sin falta', date: '2026-02-10 10:15', user: 'Cliente' },
    ],
    notes: [],
  },
  {
    id: 'CLI-0004',
    name: 'Inversiones Caribe, SRL',
    type: 'juridica',
    cedula: 'RNC 130-56789-1',
    email: 'admin@invcaribe.do',
    phone: '809-555-0404',
    whatsapp: '809-555-0404',
    address: 'Av. Winston Churchill #77, Ensanche Naco, Santo Domingo',
    status: 'active',
    segment: 'empresa',
    tier: 'gold',
    points: 520,
    source: 'directo',
    assignee: 'Admin',
    createdAt: '2025-06-01',
    lastActivity: '2026-02-10',
    totalSpent: 285000,
    totalOrders: 12,
    activeOrders: 0,
    tags: ['VIP', 'Iguala Empresarial', 'Referidor Top'],
    orders: [
      { id: 'ORD-001244', tramite: 'Contrato de Alquiler', status: 'completed', amount: 8500, date: '2026-02-06' },
      { id: 'ORD-001200', tramite: 'Registro de Marca (1 clase)', status: 'delivered', amount: 28000, date: '2026-01-05' },
    ],
    communications: [
      { type: 'call', direction: 'outbound', message: 'Reunión trimestral de iguala — todo en orden', date: '2026-02-01 15:00', user: 'Admin' },
    ],
    notes: [
      { user: 'Admin', date: '2025-06-01', text: 'Cliente fundador. Iguala empresarial desde día 1. Principal referidor.' },
    ],
  },
  {
    id: 'CLI-0005',
    name: 'Ana Fernández',
    type: 'fisica',
    cedula: '001-5551234-0',
    email: 'anaf@gmail.com',
    phone: '829-555-0505',
    whatsapp: '829-555-0505',
    address: 'Los Jardines, Santo Domingo Norte',
    status: 'active',
    segment: 'b2c',
    tier: 'bronze',
    points: 25,
    source: 'meta_ads',
    assignee: 'Paralegal Díaz',
    createdAt: '2026-02-04',
    lastActivity: '2026-02-11',
    totalSpent: 4500,
    totalOrders: 1,
    activeOrders: 0,
    tags: [],
    orders: [
      { id: 'ORD-001243', tramite: 'Certificación Buena Conducta', status: 'delivered', amount: 4500, date: '2026-02-05' },
    ],
    communications: [
      { type: 'email', direction: 'outbound', message: 'Su certificación de buena conducta está lista. Adjunto PDF.', date: '2026-02-11 09:00', user: 'Sistema' },
    ],
    notes: [],
  },
  {
    id: 'CLI-0006',
    name: 'Pedro Almonte',
    type: 'fisica',
    cedula: '012-7654321-5',
    email: 'palmonte@empresa.do',
    phone: '809-555-0606',
    whatsapp: '809-555-0606',
    address: 'Gazcue, Santo Domingo',
    status: 'active',
    segment: 'emprendedor',
    tier: 'bronze',
    points: 90,
    source: 'sim_onapi',
    assignee: 'Lic. Ramírez',
    createdAt: '2026-01-15',
    lastActivity: '2026-02-12',
    totalSpent: 18000,
    totalOrders: 1,
    activeOrders: 1,
    tags: ['Sin Respuesta'],
    orders: [
      { id: 'ORD-001242', tramite: 'Registro Reglamento Interno', status: 'needs_info', amount: 18000, date: '2026-02-07' },
    ],
    communications: [
      { type: 'call', direction: 'outbound', message: 'Llamé al cliente. Dice que envía documentos hoy.', date: '2026-02-12 09:00', user: 'Admin' },
      { type: 'whatsapp', direction: 'outbound', message: 'Sr. Almonte, necesitamos el listado de puestos y horarios.', date: '2026-02-09 11:00', user: 'Lic. Ramírez' },
    ],
    notes: [],
  },
]

export const leads = [
  {
    id: 'LEAD-0042',
    name: 'Roberto Díaz',
    email: 'rdiaz@outlook.com',
    phone: '829-555-1001',
    source: 'calc_laboral',
    interest: 'Asesoría Laboral / Demanda por desahucio',
    stage: 'new',
    score: 85,
    capturedAt: '2026-02-15',
    lastContact: null,
    assignee: null,
    data: { salario: 65000, tiempoServicio: '4 años 3 meses', liquidacion: 412750 },
  },
  {
    id: 'LEAD-0041',
    name: 'Carolina Mejía',
    email: 'cmejia@startup.do',
    phone: '809-555-1002',
    source: 'sim_onapi',
    interest: 'Registro de Marca — "FreshBowl RD"',
    stage: 'contacted',
    score: 72,
    capturedAt: '2026-02-14',
    lastContact: '2026-02-15',
    assignee: 'Lic. Peña',
    data: { marca: 'FreshBowl RD', clase: 'Clase 43 - Restaurantes', disponible: true },
  },
  {
    id: 'LEAD-0040',
    name: 'Miguel Ángel Torres',
    email: 'matorres@gmail.com',
    phone: '849-555-1003',
    source: 'calc_inmobiliaria',
    interest: 'Compraventa de inmueble — transferencia título',
    stage: 'qualified',
    score: 90,
    capturedAt: '2026-02-13',
    lastContact: '2026-02-14',
    assignee: 'Lic. Ramírez',
    data: { valorInmueble: 8500000, impuestoTransferencia: 255000, gastosNotariales: 85000 },
  },
  {
    id: 'LEAD-0039',
    name: 'Distribuidora Hernández',
    email: 'compras@disthernandez.do',
    phone: '809-555-1004',
    source: 'google_ads',
    interest: 'Constitución de Compañía + Registro de Marca',
    stage: 'proposal',
    score: 95,
    capturedAt: '2026-02-11',
    lastContact: '2026-02-14',
    assignee: 'Admin',
    data: null,
  },
  {
    id: 'LEAD-0038',
    name: 'Luisa Pichardo',
    email: 'luisap@yahoo.com',
    phone: '829-555-1005',
    source: 'gen_tyc',
    interest: 'Términos y Condiciones para e-commerce',
    stage: 'new',
    score: 45,
    capturedAt: '2026-02-14',
    lastContact: null,
    assignee: null,
    data: { tipoNegocio: 'E-commerce', tipoWeb: 'Tienda online', datosPersonales: true },
  },
  {
    id: 'LEAD-0037',
    name: 'Francisco Reyes',
    email: 'freyes@enterprise.do',
    phone: '809-555-1006',
    source: 'referido',
    interest: 'Iguala Profesional — consulta laboral recurrente',
    stage: 'negotiation',
    score: 88,
    capturedAt: '2026-02-09',
    lastContact: '2026-02-13',
    assignee: 'Admin',
    data: null,
  },
  {
    id: 'LEAD-0036',
    name: 'Diana Castillo',
    email: 'dcastillo@gmail.com',
    phone: '849-555-1007',
    source: 'diag_divorcio',
    interest: 'Divorcio — evaluación inicial',
    stage: 'contacted',
    score: 60,
    capturedAt: '2026-02-12',
    lastContact: '2026-02-13',
    assignee: 'Lic. Santos',
    data: { tipoMatrimonio: 'Civil', hijos: false, bienes: 'Sin bienes en común' },
  },
  {
    id: 'LEAD-0035',
    name: 'Importadora Global, SRL',
    email: 'legal@impglobal.do',
    phone: '809-555-1008',
    source: 'rcci',
    interest: 'Revisión de contratos de importación (IA)',
    stage: 'new',
    score: 78,
    capturedAt: '2026-02-15',
    lastContact: null,
    assignee: null,
    data: { tipoContrato: 'Importación', riesgoDetectado: 'Cláusula de penalidad excesiva' },
  },
]

export const leadStages = {
  new: { label: 'Nuevo', color: '#6366f1', bg: 'rgba(99,102,241,0.12)' },
  contacted: { label: 'Contactado', color: '#f59e0b', bg: 'rgba(245,158,11,0.12)' },
  qualified: { label: 'Cualificado', color: '#3b82f6', bg: 'rgba(59,130,246,0.12)' },
  proposal: { label: 'Propuesta', color: '#8b5cf6', bg: 'rgba(139,92,246,0.12)' },
  negotiation: { label: 'Negociación', color: '#ec4899', bg: 'rgba(236,72,153,0.12)' },
  won: { label: 'Ganado', color: '#10b981', bg: 'rgba(16,185,129,0.12)' },
  lost: { label: 'Perdido', color: '#6b7280', bg: 'rgba(107,114,128,0.12)' },
}

export const sourceLabels = {
  calc_laboral: { label: 'Calc. Laboral', color: '#f59e0b' },
  sim_onapi: { label: 'Simulador ONAPI', color: '#8b5cf6' },
  calc_inmobiliaria: { label: 'Calc. Inmobiliaria', color: '#06b6d4' },
  gen_tyc: { label: 'Generador T&C', color: '#ec4899' },
  diag_divorcio: { label: 'Diagnóstico Divorcio', color: '#ef4444' },
  rcci: { label: 'Revisión IA Contratos', color: '#10b981' },
  google_ads: { label: 'Google Ads', color: '#3b82f6' },
  meta_ads: { label: 'Meta Ads', color: '#6366f1' },
  whatsapp: { label: 'WhatsApp', color: '#22c55e' },
  referido: { label: 'Referido', color: '#f97316' },
  directo: { label: 'Directo', color: '#64748b' },
}

export const clientStats = {
  totalClients: clients.length,
  active: clients.filter(c => c.status === 'active').length,
  totalLeads: leads.length,
  newLeads: leads.filter(l => l.stage === 'new').length,
  totalRevenue: clients.reduce((sum, c) => sum + c.totalSpent, 0),
  avgTicket: Math.round(clients.reduce((sum, c) => sum + c.totalSpent, 0) / clients.reduce((sum, c) => sum + c.totalOrders, 0)),
}
