// Extended orders mock data

export const orders = [
  {
    id: 'ORD-001247',
    client: { name: 'María González', type: 'fisica', cedula: '001-1234567-8', email: 'maria@gmail.com', phone: '809-555-0101' },
    tramite: 'Constitución de Compañía (SRL)',
    category: 'societario',
    status: 'processing',
    priority: 'high',
    amount: 38000,
    amountPaid: 38000,
    paymentMethod: 'Tarjeta (Azul)',
    assignee: { name: 'Lic. Ramírez', role: 'Abogado', avatar: 'JR' },
    createdAt: '2026-02-03',
    dueDate: '2026-02-28',
    startedAt: '2026-02-04',
    slaHours: 480,
    slaUsed: 264,
    documents: [
      { name: 'Estatutos Sociales - Borrador v2.docx', status: 'review', date: '2026-02-10' },
      { name: 'Formulario DGII - RNC.pdf', status: 'pending', date: '2026-02-11' },
      { name: 'Cédula María González.pdf', status: 'uploaded', date: '2026-02-03' },
      { name: 'Comprobante de pago Cámara Comercio.pdf', status: 'uploaded', date: '2026-02-05' },
    ],
    timeline: [
      { date: '2026-02-03 09:15', event: 'Orden creada', user: 'Sistema', type: 'system' },
      { date: '2026-02-03 09:15', event: 'Pago recibido — RD$38,000 (Tarjeta Azul)', user: 'Sistema', type: 'payment' },
      { date: '2026-02-03 10:30', event: 'Asignada a Lic. Ramírez', user: 'Admin', type: 'assignment' },
      { date: '2026-02-04 08:00', event: 'Estado cambiado a "En Proceso"', user: 'Lic. Ramírez', type: 'status' },
      { date: '2026-02-05 14:20', event: 'Documentos de cliente recibidos (cédula, comprobante)', user: 'Sistema', type: 'document' },
      { date: '2026-02-10 11:45', event: 'Borrador de estatutos generado y en revisión', user: 'Lic. Ramírez', type: 'document' },
      { date: '2026-02-12 09:00', event: 'Cliente notificado — estatutos listos para revisión', user: 'Sistema', type: 'notification' },
    ],
    notes: [
      { user: 'Lic. Ramírez', date: '2026-02-10 11:50', text: 'Cliente quiere incluir 3 socios. Ajusté los estatutos con distribución 40-30-30.' },
      { user: 'Admin', date: '2026-02-06 16:00', text: 'Cliente VIP referido por Inversiones Caribe. Dar seguimiento prioritario.' },
    ],
  },
  {
    id: 'ORD-001246',
    client: { name: 'TechStart, SRL', type: 'juridica', cedula: 'RNC 131-45678-9', email: 'legal@techstart.do', phone: '829-555-0202' },
    tramite: 'Registro de Marca (1 clase)',
    category: 'pi',
    status: 'waiting_entity',
    priority: 'medium',
    amount: 28000,
    amountPaid: 28000,
    paymentMethod: 'Transferencia',
    assignee: { name: 'Lic. Peña', role: 'Abogado', avatar: 'LP' },
    createdAt: '2026-01-20',
    dueDate: '2026-06-15',
    startedAt: '2026-01-21',
    slaHours: 2400,
    slaUsed: 648,
    documents: [
      { name: 'Solicitud ONAPI - TechStart.pdf', status: 'submitted', date: '2026-01-25' },
      { name: 'Logo TechStart.png', status: 'uploaded', date: '2026-01-20' },
      { name: 'Poder de representación.pdf', status: 'uploaded', date: '2026-01-20' },
    ],
    timeline: [
      { date: '2026-01-20 14:00', event: 'Orden creada', user: 'Sistema', type: 'system' },
      { date: '2026-01-20 14:00', event: 'Pago recibido — RD$28,000 (Transferencia)', user: 'Sistema', type: 'payment' },
      { date: '2026-01-21 09:00', event: 'Asignada a Lic. Peña', user: 'Admin', type: 'assignment' },
      { date: '2026-01-25 10:30', event: 'Solicitud presentada ante ONAPI', user: 'Lic. Peña', type: 'status' },
      { date: '2026-01-25 10:35', event: 'Estado cambiado a "Esperando Entidad"', user: 'Lic. Peña', type: 'status' },
      { date: '2026-02-10 08:00', event: 'ONAPI publicó marca en boletín (período oposición 45 días)', user: 'Lic. Peña', type: 'document' },
    ],
    notes: [
      { user: 'Lic. Peña', date: '2026-02-10 08:05', text: 'Marca publicada en boletín ONAPI. Período de oposición hasta marzo 27. Si no hay objeciones, certificado en ~4 semanas después.' },
    ],
  },
  {
    id: 'ORD-001245',
    client: { name: 'José Martínez', type: 'fisica', cedula: '402-9876543-2', email: 'jose.mtz@hotmail.com', phone: '849-555-0303' },
    tramite: 'Divorcio por Mutuo Acuerdo',
    category: 'familia',
    status: 'review',
    priority: 'medium',
    amount: 35000,
    amountPaid: 17500,
    paymentMethod: 'Tarjeta (CardNET)',
    assignee: { name: 'Lic. Santos', role: 'Abogado', avatar: 'MS' },
    createdAt: '2026-02-08',
    dueDate: '2026-04-10',
    startedAt: null,
    slaHours: 960,
    slaUsed: 192,
    documents: [
      { name: 'Acta de Matrimonio.pdf', status: 'uploaded', date: '2026-02-08' },
      { name: 'Cédula José Martínez.pdf', status: 'uploaded', date: '2026-02-08' },
      { name: 'Cédula Laura Pimentel.pdf', status: 'pending', date: null },
      { name: 'Acuerdo de Bienes - Borrador.docx', status: 'draft', date: '2026-02-13' },
    ],
    timeline: [
      { date: '2026-02-08 16:30', event: 'Orden creada', user: 'Sistema', type: 'system' },
      { date: '2026-02-08 16:30', event: 'Pago parcial — RD$17,500 de RD$35,000 (CardNET)', user: 'Sistema', type: 'payment' },
      { date: '2026-02-09 09:00', event: 'Asignada a Lic. Santos', user: 'Admin', type: 'assignment' },
      { date: '2026-02-10 10:00', event: 'Solicitada cédula del cónyuge', user: 'Lic. Santos', type: 'notification' },
      { date: '2026-02-13 15:00', event: 'Borrador de acuerdo de bienes generado', user: 'Lic. Santos', type: 'document' },
    ],
    notes: [
      { user: 'Lic. Santos', date: '2026-02-10 10:05', text: 'Falta cédula del cónyuge (Laura Pimentel). Cliente dice que la envía esta semana.' },
      { user: 'Lic. Santos', date: '2026-02-13 15:05', text: 'No hay hijos menores ni bienes inmuebles en común. Caso relativamente sencillo.' },
    ],
  },
  {
    id: 'ORD-001244',
    client: { name: 'Inversiones Caribe, SRL', type: 'juridica', cedula: 'RNC 130-56789-1', email: 'admin@invcaribe.do', phone: '809-555-0404' },
    tramite: 'Contrato de Alquiler',
    category: 'contratos',
    status: 'completed',
    priority: 'low',
    amount: 8500,
    amountPaid: 8500,
    paymentMethod: 'Transferencia',
    assignee: { name: 'Paralegal Díaz', role: 'Paralegal', avatar: 'RD' },
    createdAt: '2026-02-06',
    dueDate: '2026-02-10',
    startedAt: '2026-02-06',
    slaHours: 48,
    slaUsed: 36,
    documents: [
      { name: 'Contrato de Alquiler - Final.pdf', status: 'completed', date: '2026-02-08' },
      { name: 'Cédula Propietario.pdf', status: 'uploaded', date: '2026-02-06' },
      { name: 'Cédula Inquilino.pdf', status: 'uploaded', date: '2026-02-06' },
    ],
    timeline: [
      { date: '2026-02-06 11:00', event: 'Orden creada', user: 'Sistema', type: 'system' },
      { date: '2026-02-06 11:00', event: 'Pago recibido — RD$8,500 (Transferencia)', user: 'Sistema', type: 'payment' },
      { date: '2026-02-06 11:15', event: 'Auto-asignada a Paralegal Díaz (contrato estándar)', user: 'Sistema', type: 'assignment' },
      { date: '2026-02-07 09:30', event: 'Contrato generado automáticamente', user: 'Sistema', type: 'document' },
      { date: '2026-02-07 14:00', event: 'Revisión legal completada', user: 'Paralegal Díaz', type: 'status' },
      { date: '2026-02-08 10:00', event: 'Contrato notarizado y firmado', user: 'Paralegal Díaz', type: 'document' },
      { date: '2026-02-08 10:30', event: 'Estado cambiado a "Completada"', user: 'Paralegal Díaz', type: 'status' },
    ],
    notes: [],
  },
  {
    id: 'ORD-001243',
    client: { name: 'Ana Fernández', type: 'fisica', cedula: '001-5551234-0', email: 'anaf@gmail.com', phone: '829-555-0505' },
    tramite: 'Certificación Buena Conducta',
    category: 'certificaciones',
    status: 'delivered',
    priority: 'low',
    amount: 4500,
    amountPaid: 4500,
    paymentMethod: 'Tarjeta (Azul)',
    assignee: { name: 'Paralegal Díaz', role: 'Paralegal', avatar: 'RD' },
    createdAt: '2026-02-05',
    dueDate: '2026-02-12',
    startedAt: '2026-02-05',
    slaHours: 120,
    slaUsed: 96,
    documents: [
      { name: 'Certificación Buena Conducta - PGR.pdf', status: 'completed', date: '2026-02-10' },
    ],
    timeline: [
      { date: '2026-02-05 08:30', event: 'Orden creada', user: 'Sistema', type: 'system' },
      { date: '2026-02-05 08:30', event: 'Pago recibido — RD$4,500 (Azul)', user: 'Sistema', type: 'payment' },
      { date: '2026-02-10 16:00', event: 'Certificación obtenida de PGR', user: 'Paralegal Díaz', type: 'document' },
      { date: '2026-02-11 09:00', event: 'Entregada al cliente por email', user: 'Sistema', type: 'notification' },
    ],
    notes: [],
  },
  {
    id: 'ORD-001242',
    client: { name: 'Pedro Almonte', type: 'fisica', cedula: '012-7654321-5', email: 'palmonte@empresa.do', phone: '809-555-0606' },
    tramite: 'Registro Reglamento Interno',
    category: 'laboral',
    status: 'needs_info',
    priority: 'high',
    amount: 18000,
    amountPaid: 18000,
    paymentMethod: 'Tarjeta (Azul)',
    assignee: { name: 'Lic. Ramírez', role: 'Abogado', avatar: 'JR' },
    createdAt: '2026-02-07',
    dueDate: '2026-02-28',
    startedAt: '2026-02-08',
    slaHours: 336,
    slaUsed: 216,
    documents: [
      { name: 'Reglamento Interno - Borrador.docx', status: 'draft', date: '2026-02-09' },
    ],
    timeline: [
      { date: '2026-02-07 13:00', event: 'Orden creada', user: 'Sistema', type: 'system' },
      { date: '2026-02-07 13:00', event: 'Pago recibido — RD$18,000 (Azul)', user: 'Sistema', type: 'payment' },
      { date: '2026-02-08 09:00', event: 'Asignada a Lic. Ramírez', user: 'Admin', type: 'assignment' },
      { date: '2026-02-09 11:00', event: 'Se necesita listado de puestos y horarios', user: 'Lic. Ramírez', type: 'notification' },
      { date: '2026-02-09 11:05', event: 'Estado cambiado a "Requiere Info"', user: 'Lic. Ramírez', type: 'status' },
    ],
    notes: [
      { user: 'Lic. Ramírez', date: '2026-02-09 11:10', text: 'Cliente no ha enviado listado de puestos, horarios ni políticas internas. Sin eso no puedo avanzar. Ya van 3 días.' },
      { user: 'Admin', date: '2026-02-12 09:00', text: 'Llamé al cliente. Dice que lo envía hoy. Si no responde mañana, escalar.' },
    ],
  },
  {
    id: 'ORD-001241',
    client: { name: 'Farmacia San Juan, SRL', type: 'juridica', cedula: 'RNC 131-99887-3', email: 'admin@farmsj.do', phone: '809-555-0707' },
    tramite: 'Registro de Nombre Comercial',
    category: 'pi',
    status: 'processing',
    priority: 'medium',
    amount: 18000,
    amountPaid: 18000,
    paymentMethod: 'Transferencia',
    assignee: { name: 'Lic. Peña', role: 'Abogado', avatar: 'LP' },
    createdAt: '2026-02-01',
    dueDate: '2026-04-01',
    startedAt: '2026-02-02',
    slaHours: 960,
    slaUsed: 360,
    documents: [
      { name: 'Solicitud ONAPI - Nombre Comercial.pdf', status: 'review', date: '2026-02-05' },
    ],
    timeline: [
      { date: '2026-02-01 10:00', event: 'Orden creada', user: 'Sistema', type: 'system' },
      { date: '2026-02-01 10:00', event: 'Pago recibido — RD$18,000 (Transferencia)', user: 'Sistema', type: 'payment' },
      { date: '2026-02-02 09:00', event: 'Asignada a Lic. Peña', user: 'Admin', type: 'assignment' },
      { date: '2026-02-05 14:00', event: 'Solicitud ONAPI preparada, pendiente de envío', user: 'Lic. Peña', type: 'document' },
    ],
    notes: [],
  },
  {
    id: 'ORD-001240',
    client: { name: 'Constructora del Este', type: 'juridica', cedula: 'RNC 130-11223-4', email: 'legal@coneste.do', phone: '809-555-0808' },
    tramite: 'Contrato de Compraventa Inmueble',
    category: 'inmobiliario',
    status: 'received',
    priority: 'high',
    amount: 45000,
    amountPaid: 0,
    paymentMethod: null,
    assignee: null,
    createdAt: '2026-02-16',
    dueDate: '2026-03-16',
    startedAt: null,
    slaHours: 480,
    slaUsed: 0,
    documents: [],
    timeline: [
      { date: '2026-02-16 08:45', event: 'Orden creada', user: 'Sistema', type: 'system' },
      { date: '2026-02-16 08:45', event: 'Pendiente de pago — RD$45,000', user: 'Sistema', type: 'payment' },
    ],
    notes: [
      { user: 'Sistema', date: '2026-02-16 08:45', text: 'Orden generada desde formulario web. Cliente iguala Empresarial activa.' },
    ],
  },
]

export const orderStats = {
  total: orders.length,
  received: orders.filter(o => o.status === 'received').length,
  review: orders.filter(o => o.status === 'review').length,
  processing: orders.filter(o => o.status === 'processing').length,
  waiting_entity: orders.filter(o => o.status === 'waiting_entity').length,
  completed: orders.filter(o => o.status === 'completed').length,
  delivered: orders.filter(o => o.status === 'delivered').length,
  needs_info: orders.filter(o => o.status === 'needs_info').length,
}
